### ISSUE TITLE
Crashes on iOS Safari

### ISSUE THREAD

**Issue by pulsejet** [elct9620/mruby.wasm#1]
Any fix for this?

**Comment by elct9620** [comment]
Can you paste some error message or code for me to debugging?

**Comment by pulsejet** [comment]
@elct9620 that's the problem really; it gives me absolutely nothing to work on. The tab just crashes without saying anything. I've opened an issue at https://github.com/emscripten-core/emscripten/issues/11106 ... maybe they will have some thoughts.

**Comment by elct9620** [comment]
I didn't have any iOS devices for now. But my friend test it on their iOS device is works correctly 🤔

**Comment by pulsejet** [comment]
There is something very strange happening here indeed. I can reproduce the crash only intermittently on my iPad 6 and every time on an iPad 5. Don't have an iPhone to test though. That said, a project with mruby I am working for suffers the crash on both devices (and yes, the crash is due to mruby), so I will just keep this open for now.

**Comment by elct9620** [comment]
I think it may need to use XCode to trace the crash.
And the mruby still not provide any official WebAssembly support but the information is not enough to debug for now.

**Comment by pulsejet** [comment]
I doubt even XCode would help here, since jetsam is just killing off the process and emitting a useless log event.

> the information is not enough to debug for now.

Yeah, there is _nothing_ to work on to be fair.

**Comment by pulsejet** [comment]
So apparently it crashes probably because of excessive memory usage by WebKit's optimizing compiler. I have reported the issue to Apple, will comment here if I get anything. Closing this as it has nothing to do with Mruby.

**Comment by elct9620** [comment]
Ok, thanks

By default, Emscripten is limit memory to 16K in my memory. You can try to use `-s ALLOW_MEMORY_GROWTH=1` to let it can increment the memory limit.
Reference: https://emscripten.org/docs/optimizing/Optimizing-Code.html#memory-growth

**Comment by pulsejet** [comment]
I have already tried both increasing the initial allocation and `ALLOW_MEMORY_GROWTH=1`; none works. Anyway if these were failing, it would throw up an error, not crash.

**Comment by pulsejet** [comment]
Just FYI @elct9620 this is fixed in iOS 14 beta 1

**Comment by elct9620** [comment]
Thank you information 😃
